export const QUERY_STOCK = 'QUERY_STOCK';
export const FETCH_STOCK_REQUEST = 'FETCH_STOCK_REQUEST';
export const FETCH_STOCK_SUCCESS = 'FETCH_STOCK_SUCCESS';
export const FETCH_STOCK_ERROR = 'FETCH_STOCK_ERROR';
export const ADD_STOCK_TO_LIST = 'ADD_STOCK_TO_LIST';
